import fs from 'fs';
import mysql from 'mysql2/promise';
const cfg = JSON.parse(fs.readFileSync('./config.json', 'utf8')).db;
const c = await mysql.createConnection({ host: cfg.host, port: cfg.port, user: cfg.user, password: cfg.password || '', database: cfg.database });
const [before] = await c.query("SELECT id, LENGTH(permissions) sz FROM roles");
console.log('BEFORE:');
before.forEach(r => console.log(' ', r.id, (r.sz / 1048576).toFixed(2), 'MB'));
await c.query("UPDATE roles SET permissions = '[]'");
const [after] = await c.query("SELECT id, permissions FROM roles");
console.log('AFTER:');
after.forEach(r => console.log(' ', r.id, JSON.stringify(r.permissions).slice(0, 60)));
await c.end(); process.exit(0);
